Brian branch
SeraphShroud/ygodraftcenter pull request #1
Opened 2020-03-05 06:49 UTC by Brianified

2020-03-05 07:30 UTC, SeraphShroud requested changes
Can you edit the readme to remove mention of the server-client demo and put how to run the server with the websocket? Specifically the steps on how to start up the server and connect to the rooms (basically what you showed me in the demo)

Please install flake8 linter. You can autoformat documents by right clicking the code and clicking "Format Document" once you have it installed. It will probably require you to pip3 install autopep8.

I saw there is an app/ directory and a service/ directory. Do we need the app/ directory still or can we just move the files up? Can you consolidate the current services in the service directory?

Do we still need all the tic-tac-toe files?

2020-03-05 07:30 UTC, SeraphShroud commented on src/server/server.py
> +    logger.setLevel(logging.INFO)
There is a logging_config already in place under logging_config.ini so you don't need to set this up here. You can just call logger = logging.getLogger().

2020-03-05 07:30 UTC, SeraphShroud commented on src/server/service/draft_service.py
> +class InvalidCreationError(Exception):
Can you make an exceptions.py file and add these exceptions? I'd like to keep all the exceptions in a single file for ease of modifications.

2020-03-05 07:44 UTC, Brianified commented
> Can you edit the readme to remove mention of the server-client demo and put how to run the server with the websocket? Specifically the steps on how to start up the server and connect to the rooms (basically what you showed me in the demo)
> 
> Please install flake8 linter. You can autoformat documents by right clicking the code and clicking "Format Document" once you have it installed. It will probably require you to pip3 install autopep8.
> 
> I saw there is an app/ directory and a service/ directory. Do we need the app/ directory still or can we just move the files up? Can you consolidate the current services in the service directory?
> 
> Do we still need all the tic-tac-toe files?

app essentially handles the communication and service is the are the python scripts that do all the work for the game. I wanted to separate that distinction

2020-03-05 23:03 UTC, SeraphShroud requested changes
Once the imports are resolved and we can test the server I'll approve

2020-03-06 17:57 UTC, SeraphShroud approved these changes

2020-03-06 17:57 UTC, merged