Game logic branch
SeraphShroud/ygodraftcenter pull request #4
Opened 2020-07-01 05:34 UTC by Brianified

added websocket game logic

2020-07-01 06:18 UTC, SeraphShroud requested changes
Functionality to add:
1) When in a draft waiting lobby, everyone should be able to see everyone who is in the lobby, not just the people joining after them. Mockup page: https://app.moqups.com/fNeestatg8/view/page/a3dc6978f
2) Create an endpoint to game handler that retrieves all lobbies (open and mid-draft) with their respective room info so client can create a join lobby. Mockup page: https://app.moqups.com/fNeestatg8/view/page/a808f4dc3
3) Fix ygo_test unit test

2020-07-01 06:18 UTC, SeraphShroud commented on src/server/service/draft_service.py
> +    def createDraft(self):
rename to create_draft()

2020-07-01 06:18 UTC, SeraphShroud commented on src/server/models/draft_params.py
> +    def setMainList(self, main_list):
rename all functions to have _ such as set_main_list

2020-07-01 06:18 UTC, SeraphShroud commented on src/server/tests/test_draft_service.py
> +draftParams = DraftParams()
rename all camelcase strings to _

2020-07-02 05:20 UTC, Brianified commented on src/server/tests/test_draft_service.py
> +draftParams = DraftParams()
yeah... I'm not gonna do that its too much

2020-07-19 10:10 UTC, merged